### PR TITLE
Add Password show hide feature

### PR DESCRIPTION
**Pull request by rko0211**
Kindly review my PR,
I have added Password show hide features in Sign in and Sign up page

Resolve issue : #151

### CODE REVIEW

**Comment by Sayan044** [comment]
I've faced merge conflict, please review the PR once. 
@rko0211

**Comment by rko0211** [comment]
Kindly check it i have resolve the issue

**Comment by Sayan044** [comment]
again it shows conflict.

**Comment by rko0211** [comment]
DONE

**Pull request merged**
